/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

export function Planet(props) {
  const groupRef = useRef();
  const shapeContainer = useRef(null);
  const spheresContainer = useRef(null);
  const ringContainer = useRef(null);

  const { nodes, materials } = useGLTF("/models/Planet.glb");

  useGSAP( () => {
    const tl = gsap.timeline();
    tl.from(shapeContainer.current.position, {
      y: 5,
      duration: 3,
      ease: "circ.out",
    });
    tl.from(
      spheresContainer.current.rotation,
      {
        x: 0,
        y: Math.PI,
        z: -Math.PI,
        duration: 10,
        ease: "power1.inOut",
      },
      "-=25%",
    );
    tl.from(
      ringContainer.current.rotation,
      {
        x: 0.8,
        y: 0,
        z: 0,
        duration: 10,
        ease: "power1.inOut",
      },
      "<",
    );

  }, []);

  // 🖱️ Mouse interaction (SMOOTH GSAP)
  useEffect(() => {
    if (!groupRef.current) return;

    const rotateX = gsap.quickTo(groupRef.current.rotation, "x", {
      duration: 1.5,
      ease: "power2.out",
    });

    const rotateY = gsap.quickTo(groupRef.current.rotation, "y", {
      duration: 1.5,
      ease: "power2.out",
    });

    const handleMouseMove = (e) => {
      const x = (e.clientX / window.innerWidth) * 2 - 1;
      const y = (e.clientY / window.innerHeight) * 2 - 1;

      rotateX(-y * 0.3);
      rotateY(x * 0.5);
    };

    window.addEventListener("mousemove", handleMouseMove);

    return () => window.removeEventListener("mousemove", handleMouseMove);
  }, []);

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group ref={shapeContainer} {...props} dispose={null}>
        <group ref={spheresContainer}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere.geometry}
            material={materials["Material.002"]}
            rotation={[0, 0, 0.741]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere2.geometry}
            material={materials["Material.001"]}
            position={[0.647, 1.03, -0.724]}
            rotation={[0, 0, 0.741]}
            scale={0.223}
          />
        </group>
        <mesh
          ref={ringContainer}
          castShadow
          receiveShadow
          geometry={nodes.Ring.geometry}
          material={materials["Material.001"]}
          rotation={[-0.124, 0.123, -0.778]}
          scale={2}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Planet.glb");
